FROM python:3.10-slim

RUN apt-get update && apt-get install -y postgresql-client build-essential libpq-dev && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY src /app

RUN adduser --disabled-password app-user
USER app-user

ENV PYTHONPATH="${PYTHONPATH}:/app"
EXPOSE 8000
CMD ["python", "main.py"]